name: Daily Zorro Documentation Update

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        # Verify the crawler exists
        ls -la crawler-complete.js
      
    - name: Run crawler
      run: |
        echo "Starting Zorro documentation crawl at $(date)"
        # Run with explicit node command
        node crawler-complete.js || echo "Crawler exited with code $?"
      timeout-minutes: 30
      continue-on-error: true
      
    - name: Check crawler results
      run: |
        echo "Checking crawler output..."
        if [ -d "zorro-docs-output" ]; then
          echo "✓ Output directory exists"
          echo "Pages crawled: $(find zorro-docs-output/docs -name "*.md" 2>/dev/null | wc -l || echo 0)"
          echo "Images downloaded: $(find zorro-docs-output/images -type f 2>/dev/null | wc -l || echo 0)"
        else
          echo "✗ No output directory found"
        fi
      
    - name: Check for changes
      id: check_changes
      run: |
        git add -A
        if git diff --staged --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected"
        fi
        
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "chore: Daily documentation update $(date +%Y-%m-%d)"
        git push
        
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Documentation crawler failed - ${new Date().toISOString().split('T')[0]}`,
            body: `The daily documentation crawler failed. Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
            labels: ['bug', 'automation']
          })