name: Daily Zorro Documentation Update

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git pull
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install
        echo "✓ Dependencies installed"
        
    - name: Verify crawler exists
      run: |
        if [ -f "crawler-complete.js" ]; then
          echo "✓ crawler-complete.js found"
        else
          echo "❌ crawler-complete.js not found!"
          echo "Files in directory:"
          ls -la
          exit 1
        fi
      
    - name: Run crawler
      run: |
        echo "Starting Zorro documentation crawl at $(date)"
        node crawler-complete.js || true
      timeout-minutes: 30
      
    - name: Check crawler results
      run: |
        echo "Checking crawler output..."
        if [ -d "zorro-docs-output" ]; then
          echo "✓ Output directory exists"
          echo "Pages: $(find zorro-docs-output/docs -name "*.md" 2>/dev/null | wc -l || echo 0)"
          echo "Images: $(find zorro-docs-output/images -type f 2>/dev/null | wc -l || echo 0)"
        else
          echo "✗ No output directory found - crawler may have failed"
        fi
      
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Pull latest changes
      run: |
        echo "Pulling latest changes from remote..."
        git pull origin main --rebase || true
      
    - name: Check for changes
      id: check_changes
      run: |
        git add -A
        if git diff --staged --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected"
          git diff --staged --stat
        fi
        
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git commit -m "chore: Daily documentation update $(date +%Y-%m-%d)"
        
        # Try to push, with retry on failure
        for i in {1..3}; do
          if git push; then
            echo "✓ Successfully pushed changes"
            break
          else
            echo "Push failed, pulling and trying again (attempt $i/3)..."
            git pull origin main --rebase
            sleep 2
          fi
        done